##################################################
# JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_Service_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_Service_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_Service(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<definitions targetNamespace=\"https://supplier.jcpenney.com/trs/wsvcTktInfo/\" xmlns=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:s=\"http://www.w3.org/2001/XMLSchema\" xmlns:s0=\"https://supplier.jcpenney.com/trs/wsvcTktInfo/\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:tm=\"http://microsoft.com/wsdl/mime/textMatching/\">
  <types>
    <s:schema elementFormDefault=\"qualified\" targetNamespace=\"https://supplier.jcpenney.com/trs/wsvcTktInfo/\">
      <s:element name=\"GetTktInfo\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sInRequest\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"GetTktInfoResponse\">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"GetTktInfoResult\" type=\"s:string\"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name=\"AuthHeader\" type=\"s0:AuthHeader\"/>
      <s:complexType name=\"AuthHeader\">
        <s:sequence>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sUserID\" type=\"s:string\"/>
          <s:element maxOccurs=\"1\" minOccurs=\"0\" name=\"sPassword\" type=\"s:string\"/>
        </s:sequence>
      </s:complexType>
      <s:element name=\"string\" nillable=\"true\" type=\"s:string\"/>
    </s:schema>
  </types>
  <message name=\"GetTktInfoSoapIn\">
    <part element=\"s0:GetTktInfo\" name=\"parameters\"/>
  </message>
  <message name=\"GetTktInfoSoapOut\">
    <part element=\"s0:GetTktInfoResponse\" name=\"parameters\"/>
  </message>
  <message name=\"GetTktInfoAuthHeader\">
    <part element=\"s0:AuthHeader\" name=\"AuthHeader\"/>
  </message>
  <message name=\"GetTktInfoHttpGetIn\">
    <part name=\"sInRequest\" type=\"s:string\"/>
  </message>
  <message name=\"GetTktInfoHttpGetOut\">
    <part element=\"s0:string\" name=\"Body\"/>
  </message>
  <message name=\"GetTktInfoHttpPostIn\">
    <part name=\"sInRequest\" type=\"s:string\"/>
  </message>
  <message name=\"GetTktInfoHttpPostOut\">
    <part element=\"s0:string\" name=\"Body\"/>
  </message>
  <portType name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceSoap\">
    <operation name=\"GetTktInfo\">
      <documentation>Return information necessary to print JCPenney tickets</documentation>
      <input message=\"s0:GetTktInfoSoapIn\"/>
      <output message=\"s0:GetTktInfoSoapOut\"/>
    </operation>
  </portType>
  <portType name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpGet\">
    <operation name=\"GetTktInfo\">
      <documentation>Return information necessary to print JCPenney tickets</documentation>
      <input message=\"s0:GetTktInfoHttpGetIn\"/>
      <output message=\"s0:GetTktInfoHttpGetOut\"/>
    </operation>
  </portType>
  <portType name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpPost\">
    <operation name=\"GetTktInfo\">
      <documentation>Return information necessary to print JCPenney tickets</documentation>
      <input message=\"s0:GetTktInfoHttpPostIn\"/>
      <output message=\"s0:GetTktInfoHttpPostOut\"/>
    </operation>
  </portType>
  <binding name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceSoap\" type=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceSoap\">
    <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <operation name=\"GetTktInfo\">
      <soap:operation soapAction=\"https://supplier.jcpenney.com/trs/wsvcTktInfo/GetTktInfo\" style=\"document\"/>
      <input>
        <soap:body use=\"literal\"/>
        <soap:header message=\"s0:GetTktInfoAuthHeader\" part=\"AuthHeader\" use=\"literal\"/>
      </input>
      <output>
        <soap:body use=\"literal\"/>
      </output>
    </operation>
  </binding>
  <binding name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpGet\" type=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpGet\">
    <http:binding verb=\"GET\"/>
    <operation name=\"GetTktInfo\">
      <http:operation location=\"/GetTktInfo\"/>
      <input>
        <http:urlEncoded/>
      </input>
      <output>
        <mime:mimeXml part=\"Body\"/>
      </output>
    </operation>
  </binding>
  <binding name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpPost\" type=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpPost\">
    <http:binding verb=\"POST\"/>
    <operation name=\"GetTktInfo\">
      <http:operation location=\"/GetTktInfo\"/>
      <input>
        <mime:content type=\"application/x-www-form-urlencoded\"/>
      </input>
      <output>
        <mime:mimeXml part=\"Body\"/>
      </output>
    </operation>
  </binding>
  <service name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_Service\">
    <documentation>Retrieves JCPenney ticket information and returns it to the consumer.</documentation>
    <port binding=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceSoap\" name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceSoap\">
      <soap:address location=\"http://jsupplier1.jcpenney.com/trs/wsvcTktInfo.asmx\"/>
    </port>
    <port binding=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpGet\" name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpGet\">
      <http:address location=\"http://jsupplier1.jcpenney.com/trs/wsvcTktInfo.asmx\"/>
    </port>
    <port binding=\"s0:JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpPost\" name=\"JCPenney_x0020_Ticket_x0020_Request_x0020_Web_x0020_ServiceHttpPost\">
      <http:address location=\"http://jsupplier1.jcpenney.com/trs/wsvcTktInfo.asmx\"/>
    </port>
  </service>
</definitions>"""

    def __init__(self, post='/trs/wsvcTktInfo.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_GetTktInfo(self, ps):
        self.request = ps.Parse(GetTktInfoSoapIn.typecode)
        return GetTktInfoSoapOut()

    soapAction['https://supplier.jcpenney.com/trs/wsvcTktInfo/GetTktInfo'] = 'soap_GetTktInfo'
    root[(GetTktInfoSoapIn.typecode.nspname,GetTktInfoSoapIn.typecode.pname)] = 'soap_GetTktInfo'

    def soap_GetTktInfo(self, ps):
        self.request = ps.Parse(GetTktInfoHttpGetIn.typecode)
        return GetTktInfoHttpGetOut()

    soapAction[''] = 'soap_GetTktInfo'
    root[(GetTktInfoHttpGetIn.typecode.nspname,GetTktInfoHttpGetIn.typecode.pname)] = 'soap_GetTktInfo'

    def soap_GetTktInfo(self, ps):
        self.request = ps.Parse(GetTktInfoHttpPostIn.typecode)
        return GetTktInfoHttpPostOut()

    soapAction[''] = 'soap_GetTktInfo'
    root[(GetTktInfoHttpPostIn.typecode.nspname,GetTktInfoHttpPostIn.typecode.pname)] = 'soap_GetTktInfo'

